name: CMake

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install LLVM and Clang
        run: wget https://apt.llvm.org/llvm.sh && chmod +x llvm.sh && sudo ./llvm.sh 16

      - name: Replace clang-tidy
        if: runner.os == 'Linux'
        run: sudo cp clang-tidy-16 /usr/bin/clang-tidy -f

      - name: Install LLVM and Clang
        if: runner.os == 'MacOS'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Install GCC 12
        if: runner.os == 'Linux'
        run: sudo apt-get -y install gcc-12

      - name: Configure Linux
        if: runner.os == 'Linux'
        env:
          CC: gcc-12
          CXX: gcc-12
        working-directory: ${{github.workspace}}
        run: cmake --preset env-cc-release

      - name: Build Linux
        if: runner.os == 'Linux'
        env:
          CC: gcc-12
          CXX: gcc-12
        working-directory: ${{github.workspace}}
        run: cmake --build --preset env-cc-release

      - name: Configure Linux Clang
        if: runner.os == 'Linux'
        env:
          CC: clang-16
          CXX: clang-16
        working-directory: ${{github.workspace}}
        run: cmake --preset env-cc-release

      - name: Build Linux Clang
        if: runner.os == 'Linux'
        env:
          CC: clang-16
          CXX: clang-16
        working-directory: ${{github.workspace}}
        run: cmake --build --preset env-cc-release

      - name: Configure Windows
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}
        run: cmake --preset msvc-release
          
      - name: Build Windows
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}
        run: cmake --build --preset msvc-release

      - name: Configure MacOS
        if: runner.os == 'MacOS'
        env:
          CC: clang-13
          CXX: clang-13
        working-directory: ${{github.workspace}}
        run: cmake --preset env-cc-release

      - name: Build MacOS
        if: runner.os == 'MacOS'
        env:
          CC: clang-13
          CXX: clang-13
        working-directory: ${{github.workspace}}
        run: cmake --build --preset env-cc-release

