name: Update Documentation

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Install Doxygen
        run: sudo apt-get -y install doxygen

      - name: Install GCC 12
        run: sudo apt-get -y install gcc-12

      - name: Install xmake
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt-get -y update
          sudo apt-get -y install xmake
        shell: bash

      - name: Install Sphinx Tools
        run: |
          pip install sphinx breathe exhale myst-parser docutils pydata-sphinx-theme sphinx-sitemap
        shell: bash

      - name: Configure Linux
        env:
          CC: gcc-12
          CXX: gcc-12
        working-directory: ${{github.workspace}}
        run: xmake f -c

      - name: Build Linux
        env:
          CC: gcc-12
          CXX: gcc-12
        working-directory: ${{github.workspace}}
        run: xmake b hyperion_platform_docs

      - name: Push Docs
        if: github.ref == "refs/heads/main"
        uses: s0/git-publish-subdir-action@develop
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs/_build/html

