name: Setup
on: [workflow_call]

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install XMake
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt-get -y update
          sudo apt-get -y install xmake

      - name: Install LLVM and Clang
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
          sudo apt-get -y install clang-tidy-16

      - name: Replace clang-tidy
        run: sudo cp /usr/bin/clang-tidy-16 /usr/bin/clang-tidy -f

      - name: Install GCC 12
        run: sudo apt-get -y install gcc-12

  windows:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Setup scoop
        uses: MinoruSekine/setup-scoop@v2
        with:
          buckets: extras
          scoop_checkup: true
          scoop_update: true
          update_path: true

      - name: Setup MSVC
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Install XMake
        run: scoop install xmake

  macos:
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install XMake
        run: brew install xmake

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"

