name: CMake

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Install LLVM and Clang
        if: runner.os == 'Linux'
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 16
          sudo apt-get -y install clang-tidy-16

      - name: Install xmake
        run: |
          sudo add-apt-repository ppa:xmake-io/xmake
          sudo apt-get -y update
          sudo apt-get -y install xmake

      - name: Replace clang-tidy
        if: runner.os == 'Linux'
        run: sudo cp /usr/bin/clang-tidy-16 /usr/bin/clang-tidy -f

      - name: Install LLVM and Clang
        if: runner.os == 'MacOS'
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "13.0"

      - name: Setup MSVC
        if: runner.os == 'Windows'
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Install GCC 12
        if: runner.os == 'Linux'
        run: sudo apt-get -y install gcc-12

      - name: Configure Linux
        if: runner.os == 'Linux'
        env:
          CC: gcc-12
          CXX: gcc-12
        working-directory: ${{github.workspace}}
        run: xmake f -c -y --toolchain=envs

      - name: Build Linux
        if: runner.os == 'Linux'
        env:
          CC: gcc-12
          CXX: gcc-12
        working-directory: ${{github.workspace}}
        run: xmake b

      - name: Configure Linux Clang
        if: runner.os == 'Linux'
        env:
          CC: clang-16
          CXX: clang-16
        working-directory: ${{github.workspace}}
        run: |
          rm -rf build .xmake
          xmake f -c -y --toolchain=envs

      - name: Build Linux Clang
        if: runner.os == 'Linux'
        env:
          CC: clang-16
          CXX: clang-16
        working-directory: ${{github.workspace}}
        run: |
          xmake b
          xmake check clang.tidy

      - name: Configure Windows
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}
        run: xmake f -c -y --toolchain=vs
          
      - name: Build Windows
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}
        run: xmake b

      - name: Configure MacOS
        if: runner.os == 'MacOS'
        env:
          CC: clang-13
          CXX: clang-13
        working-directory: ${{github.workspace}}
        run: xmake f -c -y --toolchain=envs

      - name: Build MacOS
        if: runner.os == 'MacOS'
        env:
          CC: clang-13
          CXX: clang-13
        working-directory: ${{github.workspace}}
        run: |
          xmake b
          xmake check clang.tidy

