name: XMake

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/setup.yml
      - uses: seanmiddleditch/gha-setup-ninja@v4

      - name: Configure Linux
        if: runner.os == 'Linux'
        env:
          CC: gcc-12
          CXX: gcc-12
        working-directory: ${{github.workspace}}
        run: xmake f -c -y --toolchain=envs

      - name: Build Linux
        if: runner.os == 'Linux'
        env:
          CC: gcc-12
          CXX: gcc-12
          ACTIONS_STEP_DEBUG: true
        working-directory: ${{github.workspace}}
        run: xmake b hyperion_platform

      - name: Configure Linux Clang
        if: runner.os == 'Linux'
        env:
          CC: clang-16
          CXX: clang-16
        working-directory: ${{github.workspace}}
        run: |
          rm -rf build .xmake
          xmake f -c -y --toolchain=envs

      - name: Build Linux Clang
        if: runner.os == 'Linux'
        env:
          CC: clang-16
          CXX: clang-16
          ACTIONS_STEP_DEBUG: true
        working-directory: ${{github.workspace}}
        run: |
          xmake b hyperion_platform
          xmake check clang.tidy

      - name: Configure Windows
        if: runner.os == 'Windows'
        working-directory: ${{github.workspace}}
        run: xmake f -c -y --toolchain=msvc
          
      - name: Build Windows
        if: runner.os == 'Windows'
        env:
          ACTIONS_STEP_DEBUG: true
        working-directory: ${{github.workspace}}
        run: xmake b hyperion_platform

      - name: Configure MacOS
        if: runner.os == 'MacOS'
        env:
          CC: clang-13
          CXX: clang-13
        working-directory: ${{github.workspace}}
        run: xmake f -c -y --toolchain=envs

      - name: Build MacOS
        if: runner.os == 'MacOS'
        env:
          CC: clang-13
          CXX: clang-13
          ACTIONS_STEP_DEBUG: true
        working-directory: ${{github.workspace}}
        run: |
          xmake b hyperion_platform
          xmake check clang.tidy

